/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app/app.index'
import { Route as AppAppTriagemRouteImport } from './routes/_app/app.triagem'
import { Route as AppAppSuporteRouteImport } from './routes/_app/app.suporte'
import { Route as AppAppSalaAdvogadoRouteImport } from './routes/_app/app.sala-advogado'
import { Route as AppAppRelatoriosRouteImport } from './routes/_app/app.relatorios'
import { Route as AppAppPublicacoesRouteImport } from './routes/_app/app.publicacoes'
import { Route as AppAppProducaoEscritorioRouteImport } from './routes/_app/app.producao-escritorio'
import { Route as AppAppProcessosRouteImport } from './routes/_app/app.processos'
import { Route as AppAppOnboardingRouteImport } from './routes/_app/app.onboarding'
import { Route as AppAppMeuQuadroRouteImport } from './routes/_app/app.meu-quadro'
import { Route as AppAppFinanceiroRouteImport } from './routes/_app/app.financeiro'
import { Route as AppAppEquipeRouteImport } from './routes/_app/app.equipe'
import { Route as AppAppDocumentosRouteImport } from './routes/_app/app.documentos'
import { Route as AppAppContratosRouteImport } from './routes/_app/app.contratos'
import { Route as AppAppConfiguracoesRouteImport } from './routes/_app/app.configuracoes'
import { Route as AppAppClientesRouteImport } from './routes/_app/app.clientes'
import { Route as AppAppAuditoriaRouteImport } from './routes/_app/app.auditoria'
import { Route as AppAppAtendimentosRouteImport } from './routes/_app/app.atendimentos'
import { Route as AppAppAgendaRouteImport } from './routes/_app/app.agenda'
import { Route as AppAppTriagemIdRouteImport } from './routes/_app/app.triagem.$id'
import { Route as AppAppQuadrosIdRouteImport } from './routes/_app/app.quadros.$id'
import { Route as AppAppProcessosIdRouteImport } from './routes/_app/app.processos.$id'
import { Route as AppAppEquipeIdRouteImport } from './routes/_app/app.equipe.$id'
import { Route as AppAppClientesIdRouteImport } from './routes/_app/app.clientes.$id'
import { Route as AppAppEquipeIdQuadroRouteImport } from './routes/_app/app.equipe.$id.quadro'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTriagemRoute = AppAppTriagemRouteImport.update({
  id: '/app/triagem',
  path: '/app/triagem',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSuporteRoute = AppAppSuporteRouteImport.update({
  id: '/app/suporte',
  path: '/app/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSalaAdvogadoRoute = AppAppSalaAdvogadoRouteImport.update({
  id: '/app/sala-advogado',
  path: '/app/sala-advogado',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRelatoriosRoute = AppAppRelatoriosRouteImport.update({
  id: '/app/relatorios',
  path: '/app/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPublicacoesRoute = AppAppPublicacoesRouteImport.update({
  id: '/app/publicacoes',
  path: '/app/publicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProducaoEscritorioRoute =
  AppAppProducaoEscritorioRouteImport.update({
    id: '/app/producao-escritorio',
    path: '/app/producao-escritorio',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppProcessosRoute = AppAppProcessosRouteImport.update({
  id: '/app/processos',
  path: '/app/processos',
  getParentRoute: () => AppRoute,
} as any)
const AppAppOnboardingRoute = AppAppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAppMeuQuadroRoute = AppAppMeuQuadroRouteImport.update({
  id: '/app/meu-quadro',
  path: '/app/meu-quadro',
  getParentRoute: () => AppRoute,
} as any)
const AppAppFinanceiroRoute = AppAppFinanceiroRouteImport.update({
  id: '/app/financeiro',
  path: '/app/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppAppEquipeRoute = AppAppEquipeRouteImport.update({
  id: '/app/equipe',
  path: '/app/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDocumentosRoute = AppAppDocumentosRouteImport.update({
  id: '/app/documentos',
  path: '/app/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppAppContratosRoute = AppAppContratosRouteImport.update({
  id: '/app/contratos',
  path: '/app/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppAppConfiguracoesRoute = AppAppConfiguracoesRouteImport.update({
  id: '/app/configuracoes',
  path: '/app/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAppClientesRoute = AppAppClientesRouteImport.update({
  id: '/app/clientes',
  path: '/app/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAuditoriaRoute = AppAppAuditoriaRouteImport.update({
  id: '/app/auditoria',
  path: '/app/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAtendimentosRoute = AppAppAtendimentosRouteImport.update({
  id: '/app/atendimentos',
  path: '/app/atendimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAgendaRoute = AppAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTriagemIdRoute = AppAppTriagemIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAppTriagemRoute,
} as any)
const AppAppQuadrosIdRoute = AppAppQuadrosIdRouteImport.update({
  id: '/app/quadros/$id',
  path: '/app/quadros/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProcessosIdRoute = AppAppProcessosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAppProcessosRoute,
} as any)
const AppAppEquipeIdRoute = AppAppEquipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAppEquipeRoute,
} as any)
const AppAppClientesIdRoute = AppAppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAppClientesRoute,
} as any)
const AppAppEquipeIdQuadroRoute = AppAppEquipeIdQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => AppAppEquipeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AppAppAgendaRoute
  '/app/atendimentos': typeof AppAppAtendimentosRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/clientes': typeof AppAppClientesRouteWithChildren
  '/app/configuracoes': typeof AppAppConfiguracoesRoute
  '/app/contratos': typeof AppAppContratosRoute
  '/app/documentos': typeof AppAppDocumentosRoute
  '/app/equipe': typeof AppAppEquipeRouteWithChildren
  '/app/financeiro': typeof AppAppFinanceiroRoute
  '/app/meu-quadro': typeof AppAppMeuQuadroRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/app/processos': typeof AppAppProcessosRouteWithChildren
  '/app/producao-escritorio': typeof AppAppProducaoEscritorioRoute
  '/app/publicacoes': typeof AppAppPublicacoesRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/sala-advogado': typeof AppAppSalaAdvogadoRoute
  '/app/suporte': typeof AppAppSuporteRoute
  '/app/triagem': typeof AppAppTriagemRouteWithChildren
  '/app/': typeof AppAppIndexRoute
  '/app/clientes/$id': typeof AppAppClientesIdRoute
  '/app/equipe/$id': typeof AppAppEquipeIdRouteWithChildren
  '/app/processos/$id': typeof AppAppProcessosIdRoute
  '/app/quadros/$id': typeof AppAppQuadrosIdRoute
  '/app/triagem/$id': typeof AppAppTriagemIdRoute
  '/app/equipe/$id/quadro': typeof AppAppEquipeIdQuadroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AppAppAgendaRoute
  '/app/atendimentos': typeof AppAppAtendimentosRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/clientes': typeof AppAppClientesRouteWithChildren
  '/app/configuracoes': typeof AppAppConfiguracoesRoute
  '/app/contratos': typeof AppAppContratosRoute
  '/app/documentos': typeof AppAppDocumentosRoute
  '/app/equipe': typeof AppAppEquipeRouteWithChildren
  '/app/financeiro': typeof AppAppFinanceiroRoute
  '/app/meu-quadro': typeof AppAppMeuQuadroRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/app/processos': typeof AppAppProcessosRouteWithChildren
  '/app/producao-escritorio': typeof AppAppProducaoEscritorioRoute
  '/app/publicacoes': typeof AppAppPublicacoesRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/sala-advogado': typeof AppAppSalaAdvogadoRoute
  '/app/suporte': typeof AppAppSuporteRoute
  '/app/triagem': typeof AppAppTriagemRouteWithChildren
  '/app': typeof AppAppIndexRoute
  '/app/clientes/$id': typeof AppAppClientesIdRoute
  '/app/equipe/$id': typeof AppAppEquipeIdRouteWithChildren
  '/app/processos/$id': typeof AppAppProcessosIdRoute
  '/app/quadros/$id': typeof AppAppQuadrosIdRoute
  '/app/triagem/$id': typeof AppAppTriagemIdRoute
  '/app/equipe/$id/quadro': typeof AppAppEquipeIdQuadroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/app/agenda': typeof AppAppAgendaRoute
  '/_app/app/atendimentos': typeof AppAppAtendimentosRoute
  '/_app/app/auditoria': typeof AppAppAuditoriaRoute
  '/_app/app/clientes': typeof AppAppClientesRouteWithChildren
  '/_app/app/configuracoes': typeof AppAppConfiguracoesRoute
  '/_app/app/contratos': typeof AppAppContratosRoute
  '/_app/app/documentos': typeof AppAppDocumentosRoute
  '/_app/app/equipe': typeof AppAppEquipeRouteWithChildren
  '/_app/app/financeiro': typeof AppAppFinanceiroRoute
  '/_app/app/meu-quadro': typeof AppAppMeuQuadroRoute
  '/_app/app/onboarding': typeof AppAppOnboardingRoute
  '/_app/app/processos': typeof AppAppProcessosRouteWithChildren
  '/_app/app/producao-escritorio': typeof AppAppProducaoEscritorioRoute
  '/_app/app/publicacoes': typeof AppAppPublicacoesRoute
  '/_app/app/relatorios': typeof AppAppRelatoriosRoute
  '/_app/app/sala-advogado': typeof AppAppSalaAdvogadoRoute
  '/_app/app/suporte': typeof AppAppSuporteRoute
  '/_app/app/triagem': typeof AppAppTriagemRouteWithChildren
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/clientes/$id': typeof AppAppClientesIdRoute
  '/_app/app/equipe/$id': typeof AppAppEquipeIdRouteWithChildren
  '/_app/app/processos/$id': typeof AppAppProcessosIdRoute
  '/_app/app/quadros/$id': typeof AppAppQuadrosIdRoute
  '/_app/app/triagem/$id': typeof AppAppTriagemIdRoute
  '/_app/app/equipe/$id/quadro': typeof AppAppEquipeIdQuadroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/agenda'
    | '/app/atendimentos'
    | '/app/auditoria'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/meu-quadro'
    | '/app/onboarding'
    | '/app/processos'
    | '/app/producao-escritorio'
    | '/app/publicacoes'
    | '/app/relatorios'
    | '/app/sala-advogado'
    | '/app/suporte'
    | '/app/triagem'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/equipe/$id'
    | '/app/processos/$id'
    | '/app/quadros/$id'
    | '/app/triagem/$id'
    | '/app/equipe/$id/quadro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/agenda'
    | '/app/atendimentos'
    | '/app/auditoria'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/meu-quadro'
    | '/app/onboarding'
    | '/app/processos'
    | '/app/producao-escritorio'
    | '/app/publicacoes'
    | '/app/relatorios'
    | '/app/sala-advogado'
    | '/app/suporte'
    | '/app/triagem'
    | '/app'
    | '/app/clientes/$id'
    | '/app/equipe/$id'
    | '/app/processos/$id'
    | '/app/quadros/$id'
    | '/app/triagem/$id'
    | '/app/equipe/$id/quadro'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/app/agenda'
    | '/_app/app/atendimentos'
    | '/_app/app/auditoria'
    | '/_app/app/clientes'
    | '/_app/app/configuracoes'
    | '/_app/app/contratos'
    | '/_app/app/documentos'
    | '/_app/app/equipe'
    | '/_app/app/financeiro'
    | '/_app/app/meu-quadro'
    | '/_app/app/onboarding'
    | '/_app/app/processos'
    | '/_app/app/producao-escritorio'
    | '/_app/app/publicacoes'
    | '/_app/app/relatorios'
    | '/_app/app/sala-advogado'
    | '/_app/app/suporte'
    | '/_app/app/triagem'
    | '/_app/app/'
    | '/_app/app/clientes/$id'
    | '/_app/app/equipe/$id'
    | '/_app/app/processos/$id'
    | '/_app/app/quadros/$id'
    | '/_app/app/triagem/$id'
    | '/_app/app/equipe/$id/quadro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/triagem': {
      id: '/_app/app/triagem'
      path: '/app/triagem'
      fullPath: '/app/triagem'
      preLoaderRoute: typeof AppAppTriagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/suporte': {
      id: '/_app/app/suporte'
      path: '/app/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppAppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/sala-advogado': {
      id: '/_app/app/sala-advogado'
      path: '/app/sala-advogado'
      fullPath: '/app/sala-advogado'
      preLoaderRoute: typeof AppAppSalaAdvogadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/relatorios': {
      id: '/_app/app/relatorios'
      path: '/app/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppAppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/publicacoes': {
      id: '/_app/app/publicacoes'
      path: '/app/publicacoes'
      fullPath: '/app/publicacoes'
      preLoaderRoute: typeof AppAppPublicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/producao-escritorio': {
      id: '/_app/app/producao-escritorio'
      path: '/app/producao-escritorio'
      fullPath: '/app/producao-escritorio'
      preLoaderRoute: typeof AppAppProducaoEscritorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/processos': {
      id: '/_app/app/processos'
      path: '/app/processos'
      fullPath: '/app/processos'
      preLoaderRoute: typeof AppAppProcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/onboarding': {
      id: '/_app/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppAppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/meu-quadro': {
      id: '/_app/app/meu-quadro'
      path: '/app/meu-quadro'
      fullPath: '/app/meu-quadro'
      preLoaderRoute: typeof AppAppMeuQuadroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/financeiro': {
      id: '/_app/app/financeiro'
      path: '/app/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppAppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/equipe': {
      id: '/_app/app/equipe'
      path: '/app/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppAppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/documentos': {
      id: '/_app/app/documentos'
      path: '/app/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppAppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/contratos': {
      id: '/_app/app/contratos'
      path: '/app/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppAppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/configuracoes': {
      id: '/_app/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppAppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/clientes': {
      id: '/_app/app/clientes'
      path: '/app/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppAppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/auditoria': {
      id: '/_app/app/auditoria'
      path: '/app/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/atendimentos': {
      id: '/_app/app/atendimentos'
      path: '/app/atendimentos'
      fullPath: '/app/atendimentos'
      preLoaderRoute: typeof AppAppAtendimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/agenda': {
      id: '/_app/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/triagem/$id': {
      id: '/_app/app/triagem/$id'
      path: '/$id'
      fullPath: '/app/triagem/$id'
      preLoaderRoute: typeof AppAppTriagemIdRouteImport
      parentRoute: typeof AppAppTriagemRoute
    }
    '/_app/app/quadros/$id': {
      id: '/_app/app/quadros/$id'
      path: '/app/quadros/$id'
      fullPath: '/app/quadros/$id'
      preLoaderRoute: typeof AppAppQuadrosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/processos/$id': {
      id: '/_app/app/processos/$id'
      path: '/$id'
      fullPath: '/app/processos/$id'
      preLoaderRoute: typeof AppAppProcessosIdRouteImport
      parentRoute: typeof AppAppProcessosRoute
    }
    '/_app/app/equipe/$id': {
      id: '/_app/app/equipe/$id'
      path: '/$id'
      fullPath: '/app/equipe/$id'
      preLoaderRoute: typeof AppAppEquipeIdRouteImport
      parentRoute: typeof AppAppEquipeRoute
    }
    '/_app/app/clientes/$id': {
      id: '/_app/app/clientes/$id'
      path: '/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppAppClientesIdRouteImport
      parentRoute: typeof AppAppClientesRoute
    }
    '/_app/app/equipe/$id/quadro': {
      id: '/_app/app/equipe/$id/quadro'
      path: '/quadro'
      fullPath: '/app/equipe/$id/quadro'
      preLoaderRoute: typeof AppAppEquipeIdQuadroRouteImport
      parentRoute: typeof AppAppEquipeIdRoute
    }
  }
}

interface AppAppClientesRouteChildren {
  AppAppClientesIdRoute: typeof AppAppClientesIdRoute
}

const AppAppClientesRouteChildren: AppAppClientesRouteChildren = {
  AppAppClientesIdRoute: AppAppClientesIdRoute,
}

const AppAppClientesRouteWithChildren = AppAppClientesRoute._addFileChildren(
  AppAppClientesRouteChildren,
)

interface AppAppEquipeIdRouteChildren {
  AppAppEquipeIdQuadroRoute: typeof AppAppEquipeIdQuadroRoute
}

const AppAppEquipeIdRouteChildren: AppAppEquipeIdRouteChildren = {
  AppAppEquipeIdQuadroRoute: AppAppEquipeIdQuadroRoute,
}

const AppAppEquipeIdRouteWithChildren = AppAppEquipeIdRoute._addFileChildren(
  AppAppEquipeIdRouteChildren,
)

interface AppAppEquipeRouteChildren {
  AppAppEquipeIdRoute: typeof AppAppEquipeIdRouteWithChildren
}

const AppAppEquipeRouteChildren: AppAppEquipeRouteChildren = {
  AppAppEquipeIdRoute: AppAppEquipeIdRouteWithChildren,
}

const AppAppEquipeRouteWithChildren = AppAppEquipeRoute._addFileChildren(
  AppAppEquipeRouteChildren,
)

interface AppAppProcessosRouteChildren {
  AppAppProcessosIdRoute: typeof AppAppProcessosIdRoute
}

const AppAppProcessosRouteChildren: AppAppProcessosRouteChildren = {
  AppAppProcessosIdRoute: AppAppProcessosIdRoute,
}

const AppAppProcessosRouteWithChildren = AppAppProcessosRoute._addFileChildren(
  AppAppProcessosRouteChildren,
)

interface AppAppTriagemRouteChildren {
  AppAppTriagemIdRoute: typeof AppAppTriagemIdRoute
}

const AppAppTriagemRouteChildren: AppAppTriagemRouteChildren = {
  AppAppTriagemIdRoute: AppAppTriagemIdRoute,
}

const AppAppTriagemRouteWithChildren = AppAppTriagemRoute._addFileChildren(
  AppAppTriagemRouteChildren,
)

interface AppRouteChildren {
  AppAppAgendaRoute: typeof AppAppAgendaRoute
  AppAppAtendimentosRoute: typeof AppAppAtendimentosRoute
  AppAppAuditoriaRoute: typeof AppAppAuditoriaRoute
  AppAppClientesRoute: typeof AppAppClientesRouteWithChildren
  AppAppConfiguracoesRoute: typeof AppAppConfiguracoesRoute
  AppAppContratosRoute: typeof AppAppContratosRoute
  AppAppDocumentosRoute: typeof AppAppDocumentosRoute
  AppAppEquipeRoute: typeof AppAppEquipeRouteWithChildren
  AppAppFinanceiroRoute: typeof AppAppFinanceiroRoute
  AppAppMeuQuadroRoute: typeof AppAppMeuQuadroRoute
  AppAppOnboardingRoute: typeof AppAppOnboardingRoute
  AppAppProcessosRoute: typeof AppAppProcessosRouteWithChildren
  AppAppProducaoEscritorioRoute: typeof AppAppProducaoEscritorioRoute
  AppAppPublicacoesRoute: typeof AppAppPublicacoesRoute
  AppAppRelatoriosRoute: typeof AppAppRelatoriosRoute
  AppAppSalaAdvogadoRoute: typeof AppAppSalaAdvogadoRoute
  AppAppSuporteRoute: typeof AppAppSuporteRoute
  AppAppTriagemRoute: typeof AppAppTriagemRouteWithChildren
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppQuadrosIdRoute: typeof AppAppQuadrosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAgendaRoute: AppAppAgendaRoute,
  AppAppAtendimentosRoute: AppAppAtendimentosRoute,
  AppAppAuditoriaRoute: AppAppAuditoriaRoute,
  AppAppClientesRoute: AppAppClientesRouteWithChildren,
  AppAppConfiguracoesRoute: AppAppConfiguracoesRoute,
  AppAppContratosRoute: AppAppContratosRoute,
  AppAppDocumentosRoute: AppAppDocumentosRoute,
  AppAppEquipeRoute: AppAppEquipeRouteWithChildren,
  AppAppFinanceiroRoute: AppAppFinanceiroRoute,
  AppAppMeuQuadroRoute: AppAppMeuQuadroRoute,
  AppAppOnboardingRoute: AppAppOnboardingRoute,
  AppAppProcessosRoute: AppAppProcessosRouteWithChildren,
  AppAppProducaoEscritorioRoute: AppAppProducaoEscritorioRoute,
  AppAppPublicacoesRoute: AppAppPublicacoesRoute,
  AppAppRelatoriosRoute: AppAppRelatoriosRoute,
  AppAppSalaAdvogadoRoute: AppAppSalaAdvogadoRoute,
  AppAppSuporteRoute: AppAppSuporteRoute,
  AppAppTriagemRoute: AppAppTriagemRouteWithChildren,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppQuadrosIdRoute: AppAppQuadrosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
